name: Test build for production


on:
  push:
    branch: "master"
  workflow_dispatch:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
        

      - name: Install dependencies
        env:
          PUBLIC_PB_URL: ${{ secrets.PUBLIC_PB_URL }}
        run: |
          pnpm install
      - name: build

        run: |
          pnpm run build